<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
<table>
    <tr>
        <td>아이디</td>
        <td></td>
    </tr>
    <tr>
        <td>회원등급</td>
        <td></td>
    </tr>
    <tr>
        <td>비밀번호</td>
        <td></td>
    </tr>
    <tr>
        <td>이름</td>
        <td></td>
    </tr>
    <tr>
        <td>성별</td>
        <td></td>
    </tr>
    <tr>
        <td>나이</td>
        <td></td>
    </tr>
    <tr>
        <td>이메일</td>
        <td></td>
    </tr>
    <tr>
        <td>전화번호</td>
        <td></td>
    </tr>
    <tr>
        <td>주소</td>
        <td></td>
    </tr>
    <tr>
        <td>계정생성일자</td>
        <td></td>
    </tr>
</table>
</body>
</html>