INSERT INTO MEMBER values('admin','1234','관리자','남','2000/01/01','admin@naver.com','관리실','01000000000',sysdate,'관리자',1);
SELECT * FROM MEMBER;
SELECT * FROM BIKE;
SELECT * FROM PURCHASE_HISTORY;
SELECT * FROM TICKET;
SELECT * FROM NOTICE_IMAGE;
SELECT * FROM (SELECT ROWNUM AS RNUM, M.* FROM (SELECT * FROM bike WHERE RENTAL_AVAILABILITY LIKE 'Y')M) WHERE RNUM BETWEEN 1 AND 5