INSERT INTO MEMBER values('admin','1234','관리자','남','2000/01/01','admin@naver.com','관리실','01000000000',sysdate,'관리자',1);
SELECT * FROM MEMBER;
SELECT * FROM BIKE;
SELECT * FROM PURCHASE_HISTORY;
SELECT * FROM TICKET;
SELECT * FROM NOTICE_IMAGE;
SELECT * FROM NOTICE_BOARD;
DELETE FROM BIKE WHERE BIKE_ID =55;
INSERT INTO BIKE values(51, '고장', SYSDATE, 1, 'N');
INSERT INTO BIKE values(52, '고장', SYSDATE, 1, 'Y');
INSERT INTO BIKE values(53, '고장', SYSDATE, 1, 'N');
INSERT INTO BIKE values(54, '정상', SYSDATE, 1, 'Y');
INSERT INTO BIKE values(54, '정상', SYSDATE, 1, 'N');
UPDATE BIKE SET 